### ISSUE TITLE
Discrepancy between docs and out?????.dat

### ISSUE THREAD

**Issue by mrosseel** [kirxkirx/vast#5]
In the description (at http://scan.sai.msu.ru/vast/) of the columns in the lightcurve files (out*.dat) there are 7 column names:
```
- 1st column - JD(TT) (default) or JD(UTC) (if VaST was started with "-u" flag)
- 2nd column - magnitude (with respect to the background level on the reference image if an absolute calibration was not done yet)
- 3rd column - estimated magnitude error
- 4th column - X position of the star on the current frame (in pixels)
- 5th column - Y position of the star on the current frame (in pixels)
- 6th column - diameter of the circular aperture used to measure the current frame (in pixels)
- 7th column - file path corresponding to the current frame 
```

In my output file there are however 10 extra columns, probably 5 comparison stars with mag + mag error or something similar. Could you explain this + where can I find which 5 stars are used for this.

**Comment by kirxkirx** [comment]
These are not the magnitudes of comparison stars, these are the differences between magnitudes measured for this same source using apertures of different diameters. These columns are mostly intended for internal VaST use when `--selectbestaperture` option is specified for processing.

I've added the following explantation to the VaST page
> Additional columns might be present in the files produced by the latest version of VaST. These might include: the differences between magnitudes of the source measured using concentric circular apertures of different diameters and the associated errors. The first of these columns will be the magnitude measured the aperture specified in the column 6. This difference is non-zero if VaST is operating in the PSF-fitting photometry mode (and column 3 lists PSF-fitting magnitudes). The following column represent measurements measured with apertures that are 10% smaller, 10% larger, 20% larger and 30%larger than the aperture specified in column 6. The difference between the sizes of the reference aperture and additional apertures may be tuned by changing the parameters AP01 to AP04 in src/vast_limits.h (and recompiling VaST with make). These magnitude difference columns are not intended to be used by user directly. Instead, they are used by lib/select_aperture_with_smallest_scatter_for_each_object routine that might be started manually or by running the analysis with --selectbestaperture option passed to ./vast. The routine will select for each object the aperture size that minimizes the lightcurve scatter. For brighter objects, a larger aperture might be more appropriate than the default one selected by VaST, while for the fainter and blended objects the smaller aperture might be more favorable. Also, the VaST has the possibility to save values of keywords from the header of an image associated with each measurement. The keyword names should be listed in vast_list_of_FITS_keywords_to_record_in_lightcurves.txt, see the examples in vast_list_of_FITS_keywords_to_record_in_lightcurves.txt_example. This might be useful to record values of external parameters (such as the airmass) that might be useful for decorrelating the lightcurves. (The external parameter decorrelation is not implemented in VaST yet, use VARTOOLS). 

Does the above explanation make sense?

**Comment by mrosseel** [comment]
Yes that makes sense, thanks, good that it's added in the docs.

There's one unsolved problem (for me): using my own software I'm generating AAVSO reports for various out*.dat files, after magnitude calibration. So the magnitude in these files should be correct (I'm assuming), but I don't know which comparison stars were used for this, which is needed in the AAVSO report. 

I've seen there's a `aavso_format.sh` script but as far as I can tell you're not using the comparison star information input to do any calculations. So I'm a bit confused as to its purpose.

**Comment by mrosseel** [comment]
this question has been answered, I've been able to resolve the other questions using my own code but some clarifications there would be welcome maybe for others.
